language: java

sudo: false

install: mvn clean install -Dgpg.skip

jdk:
  - oraclejdk8
  
before_install: 
  - git clone https://github.com/open-amdocs/zusammen-commons.git ~/builds/open-amdocs/zusammen-commons 
  - pushd ~/builds/open-amdocs/zusammen-commons
  - mvn clean install -Dgpg.skip
  - popd
  - git clone https://github.com/open-amdocs/zusammen.git ~/builds/open-amdocs/zusammen 
  - pushd ~/builds/open-amdocs/zusammen
  - mvn clean install -Dgpg.skip
  - popd

services:
  - cassandra
  
# safelist
branches:
  only:
  - master

after_success:
  - bash <(curl -s https://codecov.io/bash)

#Build notification messages , upun build status 
notifications: 
  email:
    recipients:
      - Zohar.Sacks@amdocs.com
      - Halfon.Tal@amdocs.com
      - elhay.efrat1@amdocs.com
      - SHALOMB@Amdocs.com
      - Tali.Grama@amdocs.com
      - liron.shtraichman@amdocs.com
